sudo: required

language : generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t zzarbttoo/docker-react-app -f ./docker-react-app/Dockerfile.dev ./docker-react-app

script:
  - docker run -e CI=true zzarbttoo/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"

